"""add index_name for search

Revision ID: 6567b953ab50
Revises: c58c87b84730
Create Date: 2025-05-09 00:05:53.725823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6567b953ab50'
down_revision: Union[str, None] = 'c58c87b84730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('index_name', sa.String(), nullable=False))
    op.alter_column('files', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'index_name')
    # ### end Alembic commands ###
