"""add file path

Revision ID: a632b48579c0
Revises: 4c7b742cfc91
Create Date: 2025-05-02 23:40:30.263015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a632b48579c0'
down_revision: Union[str, None] = '4c7b742cfc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
