"""not null for link and path

Revision ID: c58c87b84730
Revises: 591c8559169b
Create Date: 2025-05-08 23:56:38.471628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58c87b84730'
down_revision: Union[str, None] = '591c8559169b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
